## Pemrograman Dinamis

## Konsep

Pemrograman dinamis merupakan strategi untuk mendesain suatu algoritma, sama halnya seperti divide and conquer dan juga algoritma greedy. Kata 'pemrograman' sendiri bukan berarti bahasa pemrograman, tetapi maknanya lebih ke arah permasalahan optimasi, seperti 'pemrograman' linear.

Idenya adalah:
* Overlapping substruktur: sama halnya dengan divide and conquer
* Substruktur optimal: solusi optimal dari masalah yang berisi solusi optimal dari submasalah.
* Menyelesaikan secara bottom-up


## Knapsack Problem

Diberikan beberapa barang yang memiliki _berat_ dan _nilai_. Kemudian barang tersebut disimpan ke dalam kantong dengan _kapasitas_ yang terbatas. Sehingga _berat total_ barang yang diambil __tidak boleh__ lebih dari kapasistas kantong. Ada dua versi dari knapsack problem ini:

1. __0-1 knapsack problem__: kuantitas barangnya tidak boleh dipecah (indivisible), apakah kita ingin mengambil barang tersebut atau tidak. 
2. __fractional knapsack problem__: kuantitas barangnya dapat berbentuk pecahan (divisible), kita dapat mengambil barang dalam bentuk pecahan.

Secara umum 0-1 knapsack problem dapat ditulis sebagai berikut:
* Suatu kantong dengan kapasitas maksimum $K$, dan terdapat himpunan $S$ sebagai himpunan dari $n$ barang.
* Masing-masing barang memiliki berat $w$ dan nilai $p_i$.
* Tujuannya: Mencari barang-barang yang dapat dibawa oleh kantong tersebut dengan nilai yang optimal.

Secara matematis 0-1 knapsack problem dapat ditulis ke dalam

$$
\max \sum_{i \in S} p_i \hspace{1.5em} \text{kendala} \sum_{i \in S} w_i \leq K
$$

📌 Menggunakan __brute force__ pada masalah ini membutuhkan waktu komputasi $O(2^n)$.

### Definisikan subproblem

Misalkan barang-barang tersebut kita beri label $1, 2,\cdots, n$. Subproblemnya adalah mencari solusi optimal $S_k = \{ 1, 2, \cdots, k \}$, dimana $S_k \subseteq S$, untuk suatu $k$. Terdapat suatu parameter $w$ yang menyatakan....

### Contoh

Jika ibu Ani memiliki kantong dengan kapasistas $K=5$ dan diberikan sejumlah barang
 
|  | $x_1$ | $x_2$ | $x_3$ | $x_4$ |
|:--:|:--------:|:-------:|:-----:|:--------:|
|Profit ($p$)| 10  | 5     | 15  | 7     |
|Berat ($w$)| 2   | 3     | 5   | 7      |

Bagaimana cara menentukan keuntungan maksimumnya?

Kita lihat solusinya menggunakan pemrograman dinamis

Step 1: Inisialisasi

```
for k = 0 to K
    B[0,k] = 0
```
| $w_i$\k | 0 | 1 | 2 | 3 | 4 | 5 |
|:--:|:--------:|:-------:|:-----:|:--------:|:---:|:---:|
|0   |0         |0      |0      | 0    | 0       |0     |
|1   |          |       |       |      |         |     |
|2   |          |       |       |      |         |     |
|3   |          |       |       |      |         |     |
|4   |          |       |       |      |         |     |

```
for i = 0 to n
    B[i,0] = 0
```
| $w_i$\k | 0 | 1 | 2 | 3 | 4 | 5 |
|:--:|:--------:|:-------:|:-----:|:--------:|:---:|:---:|
|0   |0         |0      |0      | 0    | 0       |0     |
|1   |0          |       |       |      |         |     |
|2   |0         |       |       |      |         |     |
|3   |0          |       |       |      |         |     |
|4   |0          |       |       |      |         |     |

Step 2: Lakukan evaluasi untuk masing-masing kapasitas $k$ 

$x_1 = (10, 2), k=1$

```
if w_i <= k
    if p_i + B[i-1, k - w_i] > B[i-1, k]
        B[i,k] = p_i + B[i-1, w_i - k]
    else
        B[i,k] = B[i-1, k]
else
    B[i,k] = B[i-1, k]
```
* Sekarang: $i = 1, p_i = 10, w_i = 2, k - w_i = 1 - 2 = -1$

| $w_i$\k | 0 | 1 | 2 | 3 | 4 | 5 |
|:--:|:--------:|:-------:|:-----:|:--------:|:---:|:---:|
|0   |0         |0      |0      | 0    | 0       |0     |
|1   |0          |0       |       |      |         |     |
|2   |0         |       |       |      |         |     |
|3   |0          |       |       |      |         |     |
|4   |0          |       |       |      |         |     |

$x_1 = (10, 2), k=2,3,4,5$

```
if w_i <= k
    if p_i + B[i-1, k - w_i] > B[i-1, k]
        B[i,k] = p_i + B[i-1, w_i - k]
    else
        B[i,k] = B[i-1, k]
else
    B[i,k] = B[i-1, k]
```
* Sekarang: $i = 1, p_i = 10, w_i = 2$

| $w_i$\k | 0 | 1 | 2 | 3 | 4 | 5 |
|:--:|:--------:|:-------:|:-----:|:--------:|:---:|:---:|
|0   |0         |0      |0      | 0    | 0       |0     |
|1   |0          |0       |10       |10      |10         |10     |
|2   |0         |       |       |      |         |     |
|3   |0          |       |       |      |         |     |
|4   |0          |       |       |      |         |     |

### Contoh 1:



In [436]:
import numpy as np


def knapSack01(K, w, p):
    w.insert(0, 0)
    p.insert(0, 0)

    n = len(w)
    B = np.zeros((n, K+1))

    for i in range(1, n):
        for k in range(K+1):
            if w[i] <= k:
                B[i, k] = max(p[i] + B[i-1, k-w[i]], B[i-1, k])
            else:
                B[i, k] = B[i-1, k]
        # print(B)

    return B, B[n-1, K]


In [437]:
def cariItem(B, w):
    i, k = B.shape
    w.insert(0, 0)
    item = []
    weight = []

    i -= 1
    k -= 1
    while i > 0 and k > 0:
        if B[i, k] != B[i-1, k]:
            item.append(i-1)
            weight.append(w[i+1])
            i -= 1
            k -= w[i-1]
        else:
            i -= 1

    return item, weight


In [438]:
def cariItem2(B):
    i, k = B.shape

In [439]:
def printItems(M, best, cost, item, berat):
    items, mm, minItem = [], M, min(berat)
    K = list(range(M+1))
    # print(minItem)
    while mm >= minItem:
        idx = K.index(mm)
        items.append(best[idx])
        mm = mm - berat[item.index(best[idx])]
        # print(mm)
        # print(best[idx])
        # print(items)
    profit = cost[K.index(M)]
    return profit, items


In [440]:
#M = 12
#profit, items = printItems(M, best, cost, item, berat)
#print('Keuntungan maksimal (K = {0}): {1} dgn items = {2}'.
#      format(M, profit, str(items)))
#

In [441]:
berat = [2, 3, 4, 5]
profit = [3, 4, 5, 6]
K = 5

matriks, best = knapSack01(K, berat, profit)
best


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 3. 3. 3.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 3. 3. 3.]
 [0. 0. 3. 4. 4. 7.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 3. 3. 3.]
 [0. 0. 3. 4. 4. 7.]
 [0. 0. 3. 4. 5. 7.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 3. 3. 3.]
 [0. 0. 3. 4. 4. 7.]
 [0. 0. 3. 4. 5. 7.]
 [0. 0. 3. 4. 5. 7.]]


7.0

In [442]:
cariItem(matriks, berat)

([1, 0], [3, 2])

In [443]:
berat = [2, 3, 5, 7]
profit = [10, 5, 15, 7]
K = 5

matriks, best = knapSack01(K, berat, profit)
best


[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10.]
 [ 0.  0. 10. 10. 10. 15.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10.]
 [ 0.  0. 10. 10. 10. 15.]
 [ 0.  0. 10. 10. 10. 15.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10. 10.]
 [ 0.  0. 10. 10. 10. 15.]
 [ 0.  0. 10. 10. 10. 15.]
 [ 0.  0. 10. 10. 10. 15.]]


15.0

In [444]:
matriks.shape

(5, 6)

In [445]:
cariItem(matriks, berat)

([1, 0], [3, 2])

In [446]:
values = [
    360, 83, 59, 130, 431, 67, 230, 52, 93, 125, 670, 892, 600, 38, 48, 147,
    78, 256, 63, 17, 120, 164, 432, 35, 92, 110, 22, 42, 50, 323, 514, 28,
    87, 73, 78, 15, 26, 78, 210, 36, 85, 189, 274, 43, 33, 10, 19, 389, 276,
    312
]
weights = [
    7, 0, 30, 22, 80, 94, 11, 81, 70, 64, 59, 18, 0, 36, 3, 8, 15, 42, 9, 0,
    42, 47, 52, 32, 26, 48, 55, 6, 29, 84, 2, 4, 18, 56, 7, 29, 93, 44, 71,
    3, 86, 66, 31, 65, 0, 79, 20, 65, 52, 13
]
capacities = 850

matriks, best = knapSack01(capacities, weights, values)


[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ... 360. 360. 360.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ... 360. 360. 360.]
 [ 83.  83.  83. ... 443. 443. 443.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ... 360. 360. 360.]
 [ 83.  83.  83. ... 443. 443. 443.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ... 360. 360. 360.]
 [ 83.  83.  83. ... 443. 443. 443.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ... 360. 360. 360.]
 [ 83.  83.  8

In [447]:
best

7534.0

In [448]:
matriks

array([[   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,  360.,  360.,  360.],
       [  83.,   83.,   83., ...,  443.,  443.,  443.],
       ...,
       [ 733.,  733., 1247., ..., 7126., 7126., 7126.],
       [ 733.,  733., 1247., ..., 7264., 7264., 7292.],
       [ 733.,  733., 1247., ..., 7526., 7526., 7534.]])

In [449]:
index, wt = cariItem(matriks, weights)
index

[49,
 48,
 47,
 44,
 42,
 41,
 39,
 34,
 32,
 31,
 30,
 29,
 27,
 22,
 21,
 19,
 18,
 17,
 16,
 15,
 14,
 12,
 11,
 10,
 1,
 0]

In [450]:
np.sum(wt)

611